version: 1.1
kind: component
name: train
description: Specify the algorithm to train
tags: [examples, scikit-learn]

#查询算法定义的参数，全部罗列出来
inputs:
- {name: s3_con_name, type: str, value: s3-dbybucket-mlops, isOptional: true}
- {name: code_dir, type: str, value: algo/train/, isOptional: true}
- {name: boot_file, type: str, value: run.py, isOptional: true}
- {name: engine_image, type: str, value: polyaxon/polyaxon-examples:ml-serving, isOptional: true}
- {name: n_neighbors, type: int, isOptional: true, value: 3}
- {name: leaf_size, type: int, isOptional: true, value: 30}
- {name: metric, type: str, isOptional: true, value: minkowski}
- {name: p, type: int, isOptional: true, value: 2}
- {name: weights, type: str, isOptional: true, value: uniform}
- {name: test_size, type: float, isOptional: true, value: 0.3}
- {name: random_state, type: int, isOptional: true, value: 33}

#需要指定输出路径时通过输出来传参
# outputs:
# - {name: loss, type: float}
# - {name: accuracy, type: float}

run:
  kind: job
  init:
  #git方式加载训练代码
  # - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
  #s3方式加载训练代码
  - connection: "{{ s3_con_name }}"
    #s3文件下载的根目录
    artifacts:
      dirs: 
      - ["{{ code_dir }}" , "{{ globals.artifacts_path }}/code/"]
  container:
    #官网镜像，运行代码
    image: "{{ engine_image }}"
    imagePullPolicy: IfNotPresent
    #自定义镜像，运行具体引擎的代码
    #指定代码目录
    workingDir: "{{ globals.artifacts_path }}/code/"
    #使用python运行默认的训练脚本
    command: ["python","-u", "{{ boot_file }}"]
    args: [
      "--n_neighbors={{ n_neighbors }}",
      "--leaf_size={{ leaf_size }}",
      "--metric={{ metric }}",
      "--p={{ p }}",
      "--weights={{ weights }}",
      "--test_size={{ test_size }}",
      "--random_state={{ random_state }}"
    ]

